Compile issues on X11
* missing include header "unistd.h" (getuid())
* added -lX11 i.e GCC no longer fails with
  "undefined reference to symbol 'XInitThreads'"